### ISSUE TITLE
Install and configure Jest for webpacker unit testing

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/avalon-bundle#108]
### Description

In order to have unit test coverage for webpacker javascript, we're switching from karma in favor of jest (https://facebook.github.io/jest/) Jest seems better suited for ES6 js, has more built-in features (coverage reporting, mocking, etc) and seems much more easily configureable.

### Done Looks Like

- Jest is installed, configured.
- Basic, initial unit testing of ES6 classes and function mocks are in place.

### Tasks
- [x] Install Jest and necessary configs for babel and importing.
- [x] Research best pattern for isolated unit testing.
- [x] Set up initial tests.
