### ISSUE TITLE
Avalon Work Type in Hyrax - Edit

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#109]
### Description
Handling the UI elements where the model is exposed for editing of fields.

### Done Looks like
Edit form shows and stores new fields added from #101.

### Tasks
- [ ] Add new fields to appropriate terms arrays in the form (See http://samvera.github.io/customize-metadata-edit-form.html)
- [ ] Add new renderers (if necessary)
- [ ] Write spec tests

**Comment by cjcolvar** [comment]
Next step is to reorder the edit form fields to match: https://github.com/avalonmediasystem/avalon/blob/master/app/views/media_objects/_resource_description.html.erb
And to copy over the labels and descriptions from Avalon 6.x:
https://github.com/avalonmediasystem/avalon/blob/master/config/locales/en.yml#L24-L115
