### ISSUE TITLE
Handle multi-part fields in form and show view

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#119]
Related item and Note fields require two parts.  These need to be serialized into a string to be stored in the rdf and indexed for search and display.

### Done Looks Like
- Edit form has inputs for both parts of related item and note fields.
- Show view renders related item as a link using label
- Show view renders note as pretty string

### Tasks
- [x] Write hydra-editor `input` class for related item
- [ ] Add validation for related item field url
- [x] Write hydra-editor `input` class for note
- [x] Restrict note type using controlled vocabulary
- [ ] Validate note type
- [x] Add special indexing for related item and note

child of #175

**Comment by mcwhitaker** [comment]
WGBH has some multi-part fields implemented. Thinking of stealing their ideas on how to address the front end.

**Comment by cjcolvar** [comment]
I've been basing the UI side of our multipart field on WGBH's code.
https://github.com/WGBH-MLA/ams/blob/develop/app/views/records/edit_fields/_titles_with_types.html.erb
https://github.com/WGBH-
MLA/ams/blob/develop/app/input/multiple_titles_with_types_input.rb
https://github.com/WGBH-MLA/ams/blob/develop/app/forms/hyrax/asset_form.rb#L87-L97

**Comment by cjcolvar** [comment]
Validation work not done and will be carried over to new story:  https://github.com/samvera-labs/avalon-bundle/issues/172

Other work still needing to be done: 
Fix initialization of new input group when clicking add button
Increase test coverage
