### ISSUE TITLE
React scripts not loading on page loads sometimes

### ISSUE THREAD

**Issue by adamjarling** [samvera-labs/avalon-bundle#145]
### Descriptive summary

When clicking on a Work item that should render a MEJS React IIIF Media player, sometimes the initial page load doesn't fire the `DOMContentLoaded` event, which is the event that triggers the `ReactDOM.render` method.   This might be a Turbolinks issue with caching views?   We need some type of reliable indication via an event, that React can begin creating DOM components.

Watch the video below for more context:

https://screencast.com/t/n4T9Dybyj1ET

### Expected behavior

The React MEJS component loads on every render of the view/page.

### Actual behavior

The React MEJS component doesn't load sometimes because the `DOMContentLoaded` doesn't make it through.

### Steps to reproduce the behavior

Watch the screencast link above.

### Done Looks Like
- The React MEJS component loads on every render of the view/page.

### Tasks
- [x] Investigate whether this has anything to do with turbolinks
- [ ] Possible new tasks from above...
- [ ] Find an alternative, consistent event on the work show page which indicates DOM content is ready and React can begin rendering to the DOM.

**Comment by joncameron** [comment]
Might be helpful to get some of Chris's time, or someone else who knows Turbolinks.

**Comment by cjcolvar** [comment]
Looks like maybe we should bind to `turbolinks:load` (https://github.com/turbolinks/turbolinks/issues/9#issuecomment-184717346).

**Comment by yingfeng-iu** [comment]
This page also talks about turbolink issue with Document ready: https://thoughtbot.com/upcase/videos/turbolinks

**Comment by yingfeng-iu** [comment]
I deployed Issue#145 branch to fluorine and tested there. Currently the issue only occurs when one load work for the first time; after that loading this work or any other work is fine. One thing we could try is to add some before-cache listener to unmount the player.

**Comment by yingfeng-iu** [comment]
We added before-cache to unmount player which resolved the double-load issue. We still have this issue upon first load. I created https://github.com/samvera-labs/avalon-bundle/issues/180 for it.
