### ISSUE TITLE
Fluorine deploy fails when trying to cleanup old deploys

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#174]
Fluorine's docker setup creates files and directories owned by root when the container is run.  These files prevent the deploy from being cleaned up when newer deploys occur.  Our capistrano config currently says to keep the last 5 deploys.

## Done Looks Like
Capistrano deploys don't fail due to inability to clean up old deploys.

## Tasks
- [x] Fix Fluorine's docker setup so files aren't owned by root
OR
- [ ] Change capistrano's config to not care about old deploys
- [ ] Create script/cron job to clean up old deploys
