### ISSUE TITLE
Waveform data creation

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#193]
### Description

Create the waveform data to be consumed by the frontend.  Target BBC audiowaveform style json.

### Tasks
- [ ] Evaluate existing solutions for generating waveform data and make a decision
- [ ] Write service class which creates the waveform data
- [ ] Add ActiveFedora::File to MasterFile model for waveform data file
- [ ] Write job class which calls service class and stores into Fedora
- [ ] Enqueue job before master file is deleted
- [ ] (Optional) Port waveform creation code to ruby
- [ ] Write tests and documentation for any new configuration
