### ISSUE TITLE
0.6 Metadata Refinement

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#227]
### Descriptive summary

We will continue refinement on metadata including:

- [ ] Identify fields that need validation #171 
- [ ] Update EBUCore properties https://github.com/avalonmediasystem/avalon/issues/2634
- [ ] Implement validation in Avalon Work Type #172 
- [ ] Identify metadata for Files/Filesets apply to model #169
- [x] Compare Avalon 6 form to Avalon 7 #168 
- [x] Release version .3 of model on wiki #166 
- [ ] Implement Multi-part Fields #219
