### ISSUE TITLE
Structural Metadata Editor - UI Discussion

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#54]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1931
Originally created by @davidschober on *Wed, 17 May 2017 15:11:21 GMT*

---
## Description

We need to make a decision about how structural metadata will be edited within a hyrax-driven environment. Currently our structural metadata editor is a quick and dirty xml editor. The schema currently: https://github.com/avalonmediasystem/avalon/blob/dd9ea47de0fb4cc3bc2503b0b414e98fd2ea48ae/public/avalon_structure.xsd

An ideal solution would be to have editable fields associated parent and children which have a label and time extent so that an end user  can add a parent and the children and never have to touch the xml.

## Done looks like 

- Path forward is determined
- sketches are made of interface, ideally using a "hyrax-y" way of doing it
- if we punt on a visual, point and click editor, a clear path to that end is documented
- A review of hyrax design patterns if necessary
- break out technical stories as necessary.

## Tasks

- [ ] Review current graphical interface in Avalon
- [ ] Review current Hyrax interface and consider what a Hyrax style editor would look like
- [ ] developers review Hyrax UI patterns
- [ ] wireframes generated
