### ISSUE TITLE
define metadata  needs for Avalon in hyrax

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#57]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808
Originally created by @davidschober on *Wed, 05 Apr 2017 21:12:54 GMT*

---
## Description

In order to create a work type (or verify that a Generic Work type will fit our needs) we need to have a list of descriptive metadata we need for Avalon in Hyrax. This can build off the the work done in mods--> rdf working group, etc. 

## Done looks like

expands on #1772.
- There is a metadata comparison document
- Recommended changes to Hyrax Generic Work type and/or additional metadata fields needed for Avalon work type are documented
- Required fields are documented

## Tasks
- [ ] Metadata field comparison btw Avalon, MODS and RDF group, and Hyrax is complete
- [ ] Discussion of required vs non-required fields
- [ ] Metadata field changes needed for Generic Work type in Hyrax are documented
- [ ] Additional metadata fields needed for Avalon work type are documented
- [ ] investigation of plum (or other complex) hyrax/sufia driven tool if necessary.
