### ISSUE TITLE
Discuss use of Admin Sets/ Avalon Collections

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#63]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1809
Originally created by @davidschober on *Wed, 05 Apr 2017 21:14:24 GMT*

---
## Description

As we move into a hyrax environment, several core concepts are changing. The team needs to do a deep dive and document how we plan to use Admin sets and Workflows. Display sets are currently in flux, but we should gain a basic understanding of how those might work. 

* [Current High-level docs -- from LDCX](https://docs.google.com/document/d/1oCVnyzamH1sD3mSaqPooknfRTDYKYAsAdEx61hBm6v4/edit)

## Done looks like

A plan for Avalon's use of Hyrax Admin Sets is created, documented and stories written for implementing plan.

## Tasks

- [ ] Read the current high-level docs -- update if these are out of date. [Documentation](https://docs.google.com/document/d/1oCVnyzamH1sD3mSaqPooknfRTDYKYAsAdEx61hBm6v4/edit)
- [ ] Discuss admin sets and display sets etc
- [ ] Document how we plan to use Admin sets in a "default" Avalon install (as workflow holders, as high-level collections, etc)
- [ ] Write issues for work needed to use Admin sets / Display sets to govern workflow and display.
