### ISSUE TITLE
Create Avalon Work Type

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#76]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1773
Originally created by @davidschober on *Mon, 20 Mar 2017 15:29:11 GMT*

---
### Depends On
Decision from #1824 about whether to implement a new work type or not.
--
We've made the decision to create an AV work type for Avalon 7, so this issue now represents creating that work type.

This is broken out in:

#1821
#1822
#1854
## Done looks like
NOTE: This doesn't include actually playing the video.. We will focus on robust descriptive metadata to drive a full-featured Avalon like experience. Controlled vocabs aren't going to be taken on this issue. The goal is to replicate the descriptive metadata fields in current Avalon. This will take a lot of work from @jenyoung @jlhardes.

- [x] a content-type ~(or one each for Audio and Video)~ is added augmenting technical and descriptive metadata (if necessary) From #1808 #1772
- [x] content type allows for technical metadata
- [x] Forms allow ingestion of augmented descriptive metadata
- [x] Front end displays metadata

Note this extends work done in #1854

   + Keep track of work in community started in https://github.com/avalonmediasystem/avalon/issues/2223 
    + parent of #92   Determine scope of initial work type metadata. It should be defined by 
    + parent of #101   (Avalon Work Type model) 
    + parent of #100   (Avalon work type Show)
    + parent of #119 (Multi-part form)
