### ISSUE TITLE
Structural Metadata - Store XML

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#84]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2937
Originally created by @joncameron on *Wed, 25 Apr 2018 19:56:22 GMT*

---
### Description
Structural metadata will continue to be stored as XML in Avalon 7. This XML should have a home somewhere accessible by the application and in the object.

### Done Looks Like
- XML files containing structural metadata can be stored in an appropriate location within the object record

### Tasks
- [ ] Choose PCDM use uri for structural metadata file
- [ ] Add convenience methods to model for retrieving (if necessary)
- [ ] Write unit tests for storage and retrieval

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2937#issuecomment-384703255
Originally created by @davidschober on *Thu, 26 Apr 2018 16:22:55 GMT*

---
Issue migrated to samvera-labs/avalon-bundle#40
