### ISSUE TITLE
Properly Sizing the Player From Technical Metadata

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#88]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2914
Originally created by @joncameron on *Fri, 13 Apr 2018 14:44:48 GMT*

---
### Description
We have technical metadata containing height, width and aspect ratio information. The question now is how to use this to properly display video in MediaElement, in terms of player bounds, letterboxing/pillarboxing, stretching based on aspect ratio for non-square pixels, etc.

### Done Looks Like
- Evaluate how to represent, in the IIIF manifest and in MediaElement, video such that it is properly displayed.
- ensure that we have the technical metadata needed
- break issues as necessary

### Tasks
- [x] Have meeting to get common understanding of problem and determine what technical metadata is needed
- [x] Modify file characterization to capture more technical metadata (if necessary)
- [ ] Apply technical metadata to mediaelement
- [ ] Have player changes reviewed

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2914#issuecomment-382767267
Originally created by @davidschober on *Thu, 19 Apr 2018 14:55:22 GMT*

---
this will be driven by the IIIF manifest. We need to come to a shared understanding of what the  problem is.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2914#issuecomment-384703264
Originally created by @davidschober on *Thu, 26 Apr 2018 16:22:55 GMT*

---
Issue migrated to samvera-labs/avalon-bundle#41

**Comment by davidschober** [comment]
child of #89

**Comment by cjcolvar** [comment]
@joncameron took notes during both meetings here: https://iu.app.box.com/notes/296122732074
Final conclusion was to cleanup the notes of this story, close it, and open a new one for the list of options/wireframes of the player/video sizing to get wider input on.

**Comment by joncameron** [comment]
As per Chris's comment, a discussion occurred that will break out into new issues. The issue turned out to not simply of necessary technical metadata (which we have, comprising height, width, and aspect ratio) but also taking into account how this information needs to be transformed for use in a IIIF manifest.
