### ISSUE TITLE
Avalon Player Can Stream From a Media Server

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#90]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2203
Originally created by @joncameron on *Tue, 08 Aug 2017 21:05:19 GMT*

---
### Description
The IIIF manifest that the Avalon player consumes will contain URLs referencing media on a streaming server or servers. The Avalon player should be able to use this to actually present the video or audio content within the player. We will focus on configuration and setup through infrastructure. 

### Done looks like 

- The player can stream from wowza _or_ cloudfront
- We can store or map it via infrastructure. 
- More stories may need to be broken out/refined

### Tasks
- [x] Determine how to get/set reference/url of streaming derivative
- [x] Add field to model (if necessary)
- [ ] ~Write methods to determine streaming url (if necessary)~
- [x] Change presenter(s) to pass the streaming reference/url to IIIF manifest generation
- [x] Write unit tests (for model and presenter)
- [ ] Ensure player handles streaming urls in IIIF manifest appropriately

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2203#issuecomment-384703254
Originally created by @davidschober on *Thu, 26 Apr 2018 16:22:55 GMT*

---
Issue migrated to samvera-labs/avalon-bundle#42

**Comment by davidschober** [comment]
The work is on getting the streaming URLS into the manifest. The player will just consume them. We're not sure how hyrax is going to store stuff. That's the main question.

**Comment by jlhardes** [comment]
We expect this to crossover to the next sprint. We're realistic like that.

**Comment by mcwhitaker** [comment]
@davidschober @cjcolvar @joncameron  - I don't understand a task worth 5 points crossing over to the next sprint. Is it bigger than 5? How can we break it so it does not crossover to the next sprint?

**Comment by joncameron** [comment]
@mcwhitaker I don't exactly remember the context of that comment, but I think it may be that more stories are expected to be broken from this as work proceeds. It looks like some of the tasks might either not be necessary or will need extra stories broken out to finish our eventual done looks like.

**Comment by davidschober** [comment]
That, and I believe it was a capacity question (e.g. whether or not everyone would be available to turn the cranks that needed turning).

**Comment by cjcolvar** [comment]
@bkeese and I discussed and believe that we need a metadata field to store the streaming urls to support use cases like IU's intercom where one avalon stores records pushed into it from another avalon but doesn't move the streaming derivatives keeping the location of the streaming derivative configurable per item instead of repository wide.
Avalon 6.x is using EBUCore.locator for this: https://github.com/avalonmediasystem/avalon/blob/master/app/models/derivative.rb#L25-L27

**Comment by bkeese** [comment]
@cjcolvar, @carrickr and I talked and decided to index file metadata [id, label (aka quality), external_file_uri (streaming url)] as a multi-valued field on the FileSet (as an array of jsonified hashes). We need to choose an rdf predicate to use to relate the fileset to its files' metadata. @jlhardes @jenyoung?
