### ISSUE TITLE
structural metadata xml can be crosswalked to IIIF manifest

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#91]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2938
Originally created by @davidschober on *Wed, 25 Apr 2018 19:56:48 GMT*

---
## Description

We will be storing structural metadata as xml within a work. We need to cross walk it to the manifest for display within the player

## Done looks like
- depends on #84
- structural metadata stored as part of work is crosswalked to IIIF manifest

## Tasks
- [ ] Find latest prototype code from https://gist.github.com/cjcolvar/be9f5cf0565b9ae5edfe407853bb039f or newer code on mallorn
- [ ] Extract prototype code to presenter methods
- [ ] Update with latest changes to Presentation 3.0 spec
- [ ] Write unit tests

**Comment by cjcolvar** [comment]
Important code from that gist is https://gist.github.com/cjcolvar/be9f5cf0565b9ae5edfe407853bb039f#file-zzz_iiif_support-rb-L134-L177.
This will need to be updated to match what `iiif_manifest` needs: 
```ruby
   def ranges
     [
       ManifestRange.new(
         label: "Table of Contents",
         ranges: [
           ManifestRange.new(
             label: "Chapter 1",
             file_set_presenters: @pages
           )
         ]
       )
     ]
   end
 end

 class ManifestRange
   attr_reader :label, :ranges, :file_set_presenters
   def initialize(label:, ranges: [], file_set_presenters: [])
     @label = label
     @ranges = ranges
     @file_set_presenters = file_set_presenters
   end
 end
```

**Comment by cjcolvar** [comment]
Example structure file: https://github.com/avalonmediasystem/avalon/blob/master/spec/fixtures/structure.xml

**Comment by cjcolvar** [comment]
Changes to `iiif_manifest` in support of this story: https://github.com/samvera-labs/iiif_manifest/pull/21

**Comment by cjcolvar** [comment]
To manually add structure to an existing file set in the rails console:
```
work = ActiveFedora.find('work_id')
file_set = work.file_sets.first
# OR file_set = FileSet.find('file_set_id')
file_set.build_structure
file_set.structure.content = '<insert xml string (with escaped single quotes) here>'
file_set.structure.save!
file_set.save!
```

**Comment by yingfeng-iu** [comment]
There is some special case that the current div_to_iiif_range logic doesn't handle: if the div node has no div/span children element (I assume the XML parser will still accept this as valid format), it would become a range node with empty items  (even though it could still have a label). How does IIIF player handle such range, will it throw some error? I suppose nothing can be displayed, since there is no canvas for it. 

If we need to handle this case, we can do the following: 
- before creating a range for Div node, check if it has valid children elements, if yes then do; otherwise skip it; 
- if the above node is at root level, then we need to treat it as if no structure was defined, and create a simple range for it at root level.

**Comment by adamjarling** [comment]
@yingfeng-iu In regards to 

> "How does IIIF player handle such range, will it throw some error?"

It's still a work in progress so not entirely sure how it'd handle without seeing what the resulting manifest looks like.  If something doesn't exist, I think returning an empty array should be a reasonable assumption that the parser will skip it and not error out.

**Comment by yingfeng-iu** [comment]
Thanks for the feedback Adam. For now I put a TODO comment on the AVFileSetPresenter#structure_ng_xml method with some suggestions on how the parser shall validate the xml file and report errors, this method can opt to return an empty Nokogiri Doc as well on invalid xml. And in the code that actually consumes the parsed doc i put a check to raise exception if the unexpected scenario happens, assuming that the parser shall only return valid or empty doc.
