### ISSUE TITLE
define metadata  needs for Avalon in hyrax

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#97]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808
Originally created by @davidschober on *Wed, 05 Apr 2017 21:12:54 GMT*

---
## Description

In order to create a work type (or verify that a Generic Work type will fit our needs) we need to have a list of descriptive metadata we need for Avalon in Hyrax. This can build off the the work done in mods--> rdf working group, etc. 

## Done looks like

expands on #1772.
- There is a metadata comparison document
- Recommended changes to Hyrax Generic Work type and/or additional metadata fields needed for Avalon work type are documented
- Required fields are documented

## Tasks
- [x] Metadata field comparison btw Avalon, MODS and RDF group, and Hyrax is complete
- [x] Discussion of required vs non-required fields
- [x] Metadata field changes needed for Generic Work type in Hyrax are documented
- [x] Additional metadata fields needed for Avalon work type are documented
- [x] investigation of plum (or other complex) hyrax/sufia driven tool if necessary.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-293915630
Originally created by @jlhardes on *Thu, 13 Apr 2017 14:42:44 GMT*

---
Descriptive metadata questions: do we need to bring descriptive metadata into Hyrax as RDF properties to begin or is it better (and possible) to start with descriptive metadata as MODS XML files?

If we want to start off with RDF properties for descriptive metadata, can we update base Hyrax code so their fields that match reflect the RDF mappings we'd want to use (based on MODS and RDF Subgroup mapping recommendations)? https://docs.google.com/spreadsheets/d/1iKpx_jw5QY6-R5FH_2-HCcqdqIuJkDdP93xZyiY4tIU/edit?usp=sharing

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-292009212
Originally created by @jenyoung on *Wed, 05 Apr 2017 21:56:43 GMT*

---
@jlhardes and i have already planned to meet after standup on friday. @davidschober

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-292003132
Originally created by @davidschober on *Wed, 05 Apr 2017 21:30:05 GMT*

---
@jlhardes and @jenyoung everyone seems to be moving pretty quickly. I wonder if we can go ahead and document what we think we'd need to completely describe avalon works .

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-293914687
Originally created by @joncameron on *Thu, 13 Apr 2017 14:39:36 GMT*

---
There's a conversation to have about descriptive metadata. 
Question: What is it we want to show as far as technical metadata?

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-293915190
Originally created by @jenyoung on *Thu, 13 Apr 2017 14:41:14 GMT*

---
this will be part of the Avalon "gem"

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-293941723
Originally created by @cjcolvar on *Thu, 13 Apr 2017 16:08:20 GMT*

---
I think it would be easiest to start off with RDF only if we could get away with that.

**Comment by davidschober** [comment]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/1808#issuecomment-293915043
Originally created by @joncameron on *Thu, 13 Apr 2017 14:40:47 GMT*

---
This ticket informs what you get out of the box with an Avalon gem within Hyrax.
